name: prettier
on:
  # for pull requests from this repo
  pull_request:
  # for pull requests from forks
  pull_request_target:
  # for any pushes that may sidestep pr workflow
  push:
    branches:
    - main
    - master
    - dev/*
    - hotfix/*
jobs:
  prettier:
    # filter out the event that shouldn't apply
    # prevents running twice when not necessary
    # if push, make sure it's this repo
    # if pr, make sure it's this repo
    # if pr_target, make sure it's a fork
    if: >-
      (
        github.event_name == 'push' &&
        github.event.pull_request.head.repo.full_name == github.repository
      ) || (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name == github.repository
      ) || (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.head.repo.full_name != github.repository
      )

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: NPM - Test, Build, Deploy
      uses: actions/setup-node@v1
      with:
        node-version: 12.11.1

    - name: Cache Yarn Deps
      uses: c-hive/gha-yarn-cache@v1

    - run: yarn install --frozen-lockfile
    - run: yarn lerna run prettier:run

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        commit_message: Automated prettier formatting changes
        branch: ${{ github.head_ref }}
